"""Default-path true-oracle check via the committed SemiBin2 cache.

The cache under ``tests/fidelity/data/cache/genome_set_v1`` was generated by the
genuine in-process SemiBin2 oracle (see ``provenance.json``) and committed as
text. Loading it gives a real candidate-vs-SemiBin comparison with **no SemiBin
installed at test time** — the brief's "default path loads the cache" goal.
Regenerate with ``python -m megobin.fidelity.refresh_cache``.
"""

from pathlib import Path

import pytest

from megobin.fidelity import (
    CachedReferenceOracle,
    FidelityHarness,
    StaleCacheError,
    binner_ari,
    make_genome_fixture,
)

from .conftest import divergent_binner, faithful_binner

_CACHE_DIR = Path(__file__).parent / "data" / "cache" / "genome_set_v1"


def _oracle() -> CachedReferenceOracle:
    return CachedReferenceOracle(_CACHE_DIR)


def test_cache_is_present():
    assert (_CACHE_DIR / "provenance.json").exists()
    assert list(_CACHE_DIR.glob("run_*.csv"))


def test_provenance_records_semibin_source():
    prov = _oracle().provenance
    assert "SemiBin2" in prov["source"]
    assert prov["fixture_id"] == "genome_set_v1"


def test_faithful_passes_against_cached_semibin(genome_set):
    report = FidelityHarness(binner_ari, z=2.0).run(
        candidate=faithful_binner(genome_set), oracle=_oracle(), fixture=genome_set
    )
    assert report.passed, report.to_markdown()


def test_divergent_fails_against_cached_semibin(genome_set):
    report = FidelityHarness(binner_ari, z=2.0).run(
        candidate=divergent_binner(genome_set), oracle=_oracle(), fixture=genome_set
    )
    assert not report.passed, report.to_markdown()


def test_stale_cache_is_detected():
    # A different fixture (manifest hash mismatch) must be rejected, not silently
    # compared against the wrong reference.
    wrong = make_genome_fixture(n_noise=5, fixture_id="genome_set_v1")
    with pytest.raises(StaleCacheError):
        _oracle().runs(wrong)


def test_stale_check_uses_manifest_not_optional_property():
    # A fixture without a manifest_sha256 convenience property (e.g. blobs) must
    # still be hashed from its manifest and rejected, not silently accepted.
    from megobin.fidelity import make_blobs_fixture

    with pytest.raises(StaleCacheError):
        _oracle().runs(make_blobs_fixture())
